### ISSUE TITLE
GUI Clean Architecture 

### ISSUE THREAD

**Issue by IILIQUIDII** [matthewrhdu/sout-this_is_our_teamname-forked-CSC207H1-Project#1]
## TODOs
- [ ] Long get commands for manager
- [ ] new WebScraper in scheduleCourseHandler
- [ ] no need to import file not found and invalid input exceptions in scheduleCourseHandler
- [ ]  Referencing TimeTableManager, Task and Events in TimeTableScreen
